package com.walfud.meetu.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    private Long userId;
    private String password;
    private String nick;
    private String mood;
    private String portraitUrl;
    private String phoneNum;
    private String imei;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long userId, String password, String nick, String mood, String portraitUrl, String phoneNum, String imei) {
        this.id = id;
        this.userId = userId;
        this.password = password;
        this.nick = nick;
        this.mood = mood;
        this.portraitUrl = portraitUrl;
        this.phoneNum = phoneNum;
        this.imei = imei;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getMood() {
        return mood;
    }

    public void setMood(String mood) {
        this.mood = mood;
    }

    public String getPortraitUrl() {
        return portraitUrl;
    }

    public void setPortraitUrl(String portraitUrl) {
        this.portraitUrl = portraitUrl;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

}
